fix: deploy 테스트9호기

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,6 +22,14 @@ jobs:
       - name: Build with Gradle
         run: ./gradlew clean build
 
+      - name: Check if JAR file exists
+        run: |
+          if [ -f build/libs/korail-0.0.1-SNAPSHOT.jar ]; then
+            echo "JAR file found."
+          else
+            echo "JAR file not found!" && exit 1
+          fi
+
       - name: Upload JAR to Server
         uses: appleboy/scp-action@v0.1.4
         with:
